### ISSUE TITLE
Invalid environment variables: { DATABASE_URL: [ 'Required' ] }

### ISSUE THREAD

**Issue by fahdmirza** [JohnZolton/snorkle#1]
Hi,
 I am getting following error:

`(sn) Ubuntu@0041-kci-prxmx10005:~/snorkle$ npm start

> patense@0.1.0 start
> next start

  ▲ Next.js 14.2.7
  - Local:        http://localhost:3000

 ✓ Starting...
❌ Invalid environment variables: { DATABASE_URL: [ 'Required' ] }
 ⨯ Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Invalid environment variables
    at onValidationError (file:///home/Ubuntu/snorkle/node_modules/@t3-oss/env-core/dist/index.js:29:15)
    at createEnv (file:///home/Ubuntu/snorkle/node_modules/@t3-oss/env-core/dist/index.js:35:16)
    at createEnv (file:///home/Ubuntu/snorkle/node_modules/@t3-oss/env-nextjs/dist/index.js:12:12)
    at file:///home/Ubuntu/snorkle/src/env.js:4:20
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async file:///home/Ubuntu/snorkle/next.config.js:5:1
(sn) Ubuntu@0041-kci-prxmx10005:~/snorkle$ 
`

regards,

**Comment by fahdmirza** [comment]
I was able to fix the above by putting in .env file. But now getting following error:

sn) Ubuntu@0041-kci-prxmx10005:~/snorkle$ npm start

> patense@0.1.0 start
> next start

  ▲ Next.js 14.2.7
  - Local:        http://localhost:3000

 ✓ Starting...
Error: ENOENT: no such file or directory, open '/home/Ubuntu/snorkle/.next/prerender-manifest.json'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1242:14)
    at async setupFsCheck (/home/Ubuntu/snorkle/node_modules/next/dist/server/lib/router-utils/filesystem.js:188:40)
    at async initialize (/home/Ubuntu/snorkle/node_modules/next/dist/server/lib/router-server.js:62:23)
    at async Server.<anonymous> (/home/Ubuntu/snorkle/node_modules/next/dist/server/lib/start-server.js:249:36) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/Ubuntu/snorkle/.next/prerender-manifest.json'
}

**Comment by JohnZolton** [comment]
Had the wrong npm command, updated it to 'npm run dev', thanks

**Comment by fahdmirza** [comment]
Hi,
  its running after using npm run dev, but when I try to create a new collection, it just hangs and gives following error in terminal:

` - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 1922ms
 ○ Compiling / ...
 ✓ Compiled / in 7.3s (935 modules)
 GET / 200 in 8062ms
 ✓ Compiled in 891ms (470 modules)
 ○ Compiling /new ...
 ✓ Compiled /new in 2s (1023 modules)
 ○ Compiling /api/trpc/[trpc] ...
 ✓ Compiled /api/trpc/[trpc] in 628ms (565 modules)
prisma:query BEGIN IMMEDIATE
prisma:query INSERT INTO `main`.`Job` (`createdAt`, `updatedAt`) VALUES (?,?) RETURNING `id` AS `id`
prisma:query ROLLBACK
prisma:error 
Invalid `prisma.job.create()` invocation:


The table `main.Job` does not exist in the current database.
[TRPC] job.createJob took 425ms to execute
❌ tRPC failed on job.createJob: 
Invalid `prisma.job.create()` invocation:


The table `main.Job` does not exist in the current database.
 POST /api/trpc/job.createJob?batch=1 200 in 1804ms
 ○ Compiling /collections ...
 ✓ Compiled /collections in 732ms (1029 modules)
 ✓ Compiled /api/trpc/[trpc] in 190ms (569 modules)
prisma:query SELECT 1
prisma:query SELECT `main`.`Job`.`id`, `main`.`Job`.`createdAt`, `main`.`Job`.`updatedAt` FROM `main`.`Job` WHERE 1=1 ORDER BY `main`.`Job`.`createdAt` ASC LIMIT ? OFFSET ?
prisma:error 
Invalid `prisma.job.findMany()` invocation:


The table `main.Job` does not exist in the current database.
[TRPC] job.getAllJobs took 361ms to execute
❌ tRPC failed on job.getAllJobs: 
Invalid `prisma.job.findMany()` invocation:


The table `main.Job` does not exist in the current database.
 GET /api/trpc/job.getAllJobs?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 200 in 730ms
prisma:query SELECT `main`.`Job`.`id`, `main`.`Job`.`createdAt`, `main`.`Job`.`updatedAt` FROM `main`.`Job` WHERE 1=1 ORDER BY `main`.`Job`.`createdAt` ASC LIMIT ? OFFSET ?
prisma:error 
Invalid `prisma.job.findMany()` invocation:


The table `main.Job` does not exist in the current database.
[TRPC] job.getAllJobs took 456ms to execute
❌ tRPC failed on job.getAllJobs: 
Invalid `prisma.job.findMany()` invocation:


The table `main.Job` does not exist in the current database.
 GET /api/trpc/job.getAllJobs?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 200 in 490ms
prisma:query SELECT `main`.`Job`.`id`, `main`.`Job`.`createdAt`, `main`.`Job`.`updatedAt` FROM `main`.`Job` WHERE 1=1 ORDER BY `main`.`Job`.`createdAt` ASC LIMIT ? OFFSET ?
prisma:error 
Invalid `prisma.job.findMany()` invocation:


The table `main.Job` does not exist in the current database.
[TRPC] job.getAllJobs took 334ms to execute
❌ tRPC failed on job.getAllJobs: 
Invalid `prisma.job.findMany()` invocation:


The table `main.Job` does not exist in the current database.
 GET /api/trpc/job.getAllJobs?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 200 in 366ms
 ⨯ TypeError: Promise.withResolvers is not a function
    at __webpack_require__ (/home/Ubuntu/snorkle/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/new/page.tsx:15:67)
    at (ssr)/./src/app/new/page.tsx (/home/Ubuntu/snorkle/.next/server/app/new/page.js:173:1)
    at Object.__webpack_require__ [as require] (/home/Ubuntu/snorkle/.next/server/webpack-runtime.js:33:42)
    at JSON.parse (<anonymous>)
digest: "2343748518"
 GET /new 500 in 318ms
prisma:query SELECT `main`.`Job`.`id`, `main`.`Job`.`createdAt`, `main`.`Job`.`updatedAt` FROM `main`.`Job` WHERE 1=1 ORDER BY `main`.`Job`.`createdAt` ASC LIMIT ? OFFSET ?
prisma:error 
Invalid `prisma.job.findMany()` invocation:


The table `main.Job` does not exist in the current database.
[TRPC] job.getAllJobs took 275ms to execute
❌ tRPC failed on job.getAllJobs: 
Invalid `prisma.job.findMany()` invocation:


The table `main.Job` does not exist in the current database.
 GET /api/trpc/job.getAllJobs?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 200 in 309ms
prisma:query SELECT `main`.`Job`.`id`, `main`.`Job`.`createdAt`, `main`.`Job`.`updatedAt` FROM `main`.`Job` WHERE 1=1 ORDER BY `main`.`Job`.`createdAt` ASC LIMIT ? OFFSET ?
prisma:error 
Invalid `prisma.job.findMany()` invocation:


The table `main.Job` does not exist in the current database.
[TRPC] job.getAllJobs took 372ms to execute
❌ tRPC failed on job.getAllJobs: 
Invalid `prisma.job.findMany()` invocation:


The table `main.Job` does not exist in the current database.
 GET /api/trpc/job.getAllJobs?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 200 in 403ms
prisma:query SELECT `main`.`Job`.`id`, `main`.`Job`.`createdAt`, `main`.`Job`.`updatedAt` FROM `main`.`Job` WHERE 1=1 ORDER BY `main`.`Job`.`createdAt` ASC LIMIT ? OFFSET ?
prisma:error 
Invalid `prisma.job.findMany()` invocation:


The table `main.Job` does not exist in the current database.
[TRPC] job.getAllJobs took 349ms to execute
❌ tRPC failed on job.getAllJobs: 
Invalid `prisma.job.findMany()` invocation:


The table `main.Job` does not exist in the current database.
 GET /api/trpc/job.getAllJobs?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 200 in 377ms
 GET / 200 in 108ms
prisma:query SELECT 1
prisma:query SELECT `main`.`Job`.`id`, `main`.`Job`.`createdAt`, `main`.`Job`.`updatedAt` FROM `main`.`Job` WHERE 1=1 ORDER BY `main`.`Job`.`createdAt` ASC LIMIT ? OFFSET ?
prisma:error 
Invalid `prisma.job.findMany()` invocation:

`

Could you please review the instructions in read me , as it seems that either software hasn't been tested / or fully ready, or read me doesnt has correct information. Thanks.

**Comment by JohnZolton** [comment]
updated, needed to run 'npm run db:push' to init the db

**Comment by fahdmirza** [comment]
Thanks, it works now. I did a full video on my channel on Snorkle:

https://youtu.be/abxKnUBo6rs?si=WGHBR-N-WxNxMkFU

regards,
Fahd
